src/Entity/Bouteille.php
<?php

namespace App\Entity;

use App\Repository\BouteilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BouteilleRepository::class)
 */
class Bouteille
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="bigint", options={"unsigned"=true})
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $format;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien_produit;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $src_image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $srcset_image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $designation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $degre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $taux_sucre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $producteur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $agent_promotion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $millesime;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cepage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $region;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $produit_quebec;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pastille_gout_titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pastille_image_src;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=BouteilleCellier::class, mappedBy="bouteille")
     */
    private $bouteilleCelliers;

    /**
     * @ORM\ManyToMany(targetEntity=Cellier::class)
     * @ORM\JoinTable(name="bouteille_cellier",
     *      joinColumns={@ORM\JoinColumn(name="bouteille_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="cellier_id", referencedColumnName="id")}
     *      )
     */
    private $celliers;

    public function __construct()
    {
        $this->bouteilleCelliers = new ArrayCollection();
        $this->celliers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(?string $format): self
    {
        $this->format = $format;

        return $this;
    }

    public function getLienProduit(): ?string
    {
        return $this->lien_produit;
    }

    public function setLienProduit(?string $lien_produit): self
    {
        $this->lien_produit = $lien_produit;

        return $this;
    }

    public function getSrcImage(): ?string
    {
        return $this->src_image;
    }

    public function setSrcImage(?string $src_image): self
    {
        $this->src_image = $src_image;

        return $this;
    }

    public function getSrcsetImage(): ?string
    {
        return $this->srcset_image;
    }

    public function setSrcsetImage(?string $srcset_image): self
    {
        $this->srcset_image = $srcset_image;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(?string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getDegre(): ?string
    {
        return $this->degre;
    }

    public function setDegre(?string $degre): self
    {
        $this->degre = $degre;

        return $this;
    }

    public function getTauxSucre(): ?string
    {
        return $this->taux_sucre;
    }

    public function setTauxSucre(?string $taux_sucre): self
    {
        $this->taux_sucre = $taux_sucre;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getProducteur(): ?string
    {
        return $this->producteur;
    }

    public function setProducteur(?string $producteur): self
    {
        $this->producteur = $producteur;

        return $this;
    }

    public function getAgentPromotion(): ?string
    {
        return $this->agent_promotion;
    }

    public function setAgentPromotion(?string $agent_promotion): self
    {
        $this->agent_promotion = $agent_promotion;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getMillesime(): ?string
    {
        return $this->millesime;
    }

    public function setMillesime(?string $millesime): self
    {
        $this->millesime = $millesime;

        return $this;
    }

    public function getCepage(): ?string
    {
        return $this->cepage;
    }

    public function setCepage(?string $cepage): self
    {
        $this->cepage = $cepage;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getProduitQuebec(): ?bool
    {
        return $this->produit_quebec;
    }

    public function setProduitQuebec(?bool $produit_quebec): self
    {
        $this->produit_quebec = $produit_quebec;

        return $this;
    }

    public function getPastilleGoutTitre(): ?string
    {
        return $this->pastille_gout_titre;
    }

    public function setPastilleGoutTitre(?string $pastille_gout_titre): self
    {
        $this->pastille_gout_titre = $pastille_gout_titre;

        return $this;
    }

    public function getPastilleImageSrc(): ?string
    {
        return $this->pastille_image_src;
    }

    public function setPastilleImageSrc(?string $pastille_image_src): self
    {
        $this->pastille_image_src = $pastille_image_src;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|BouteilleCellier[]
     */
    public function getBouteilleCelliers(): Collection
    {
        return $this->bouteilleCelliers;
    }

    public function addBouteilleCellier(BouteilleCellier $bouteilleCellier): self
    {
        if (!$this->bouteilleCelliers->contains($bouteilleCellier)) {
            $this->bouteilleCelliers[] = $bouteilleCellier;
            $bouteilleCellier->setBouteille($this);
        }

        return $this;
    }

    public function removeBouteilleCellier(BouteilleCellier $bouteilleCellier): self
    {
        if ($this->bouteilleCelliers->removeElement($bouteilleCellier)) {
            // set the owning side to null (unless already changed)
            if ($bouteilleCellier->getBouteille() === $this) {
                $bouteilleCellier->setBouteille(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Cellier[]
     */
    public function getCelliers(): Collection
    {
        return $this->celliers;
    }

    public function addCellier(Cellier $cellier): self
    {
        if (!$this->celliers->contains($cellier)) {
            $this->celliers[] = $cellier;
        }

        return $this;
    }

    public function removeCellier(Cellier $cellier): self
    {
        $this->celliers->removeElement($cellier);

        return $this;
    }
}

src/Controller/BouteilleController.php
<?php


namespace App\Controller;

use App\Entity\Bouteille;
use App\Entity\Cellier;
use App\Entity\BouteilleCellier;
use App\Form\BouteilleType;
use App\Repository\BouteilleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BouteilleController extends AbstractController
{
    private $entityManager;
    private $paginator;
    private $bouteilleRepository;

    public function __construct(EntityManagerInterface $entityManager, PaginatorInterface $paginator, BouteilleRepository $bouteilleRepository)
    {
        $this->entityManager = $entityManager;
        $this->paginator = $paginator;
        $this->bouteilleRepository = $bouteilleRepository;
    }

    /**
     * @Route("/bouteilles", name="bouteille_index")
     */
    public function index(Request $request): Response
    {
        $query = $this->entityManager->getRepository(Bouteille::class)->createQueryBuilder('b')->getQuery();

        $pagination = $this->paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10
        );

        $celliers = $this->entityManager->getRepository(Cellier::class)->findBy(['user' => $this->getUser()]);

        return $this->render('bouteille/index.html.twig', [
            'pagination' => $pagination,
            'celliers' => $celliers,
        ]);
    }

    /**
     * @Route("/bouteilles/{id}", name="bouteille_show", requirements={"id"="\d+"})
     */
    public function show(Bouteille $bouteille): Response
    {
        return $this->render('bouteille/show.html.twig', [
            'bouteille' => $bouteille,
        ]);
    }

    /**
     * @Route("/bouteilles/create", name="bouteille_create")
     */
    public function create(Request $request): Response
    {
        $bouteille = new Bouteille();
        $form = $this->createForm(BouteilleType::class, $bouteille);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($bouteille);
            $this->entityManager->flush();

            return $this->redirectToRoute('bouteille_index');
        }

        return $this->render('bouteille/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/bouteilles/{id}/edit", name="bouteille_edit", requirements={"id"="\d+"})
     */
    public function edit(Request $request, Bouteille $bouteille): Response
    {
        $form = $this->createForm(BouteilleType::class, $bouteille);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            return $this->redirectToRoute('bouteille_index');
        }

        return $this->render('bouteille/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/bouteilles/{id}/delete", name="bouteille_delete", requirements={"id"="\d+"}, methods={"POST"})
     */
    public function delete(Request $request, Bouteille $bouteille): Response
    {
        if ($this->isCsrfTokenValid('delete' . $bouteille->getId(), $request->request->get('_token'))) {
            $this->entityManager->remove($bouteille);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('bouteille_index');
    }

    /**
     * @Route("/bouteilles/search", name="bouteille_search")
     */
    public function search(Request $request): Response
    {
        $searchTerm = $request->query->get('search');
        $bouteilles = $this->bouteilleRepository->findBySearchTerm($searchTerm);

        return $this->render('bouteille/show-search.html.twig', [
            'bouteilles' => $bouteilles,
        ]);
    }

    /**
     * @Route("/bouteilles/sorting", name="bouteille_sorting")
     */
    public function sorting(Request $request): Response
    {
       // throw $this->createNotFoundException('arret');
      
        $sortingCriteria = $request->query->get('sort', 'name_asc');
        $searchTerm = $request->query->get('search', null);
        //$filters = $request->query->all('filters');
        $filters = $request->query->all();
       //*************
      // $filters=[];
       //$filters['color'] = $request->query->get('color', null);
       //$filters['format'] = $request->query->get('format', null);
       
       //*************
        dump($request->query->all());
        dump($sortingCriteria,$searchTerm,$filters);

        $bouteilles = $this->bouteilleRepository->findBySortingCriteria($sortingCriteria, $searchTerm, $filters);

        return $this->render('bouteille/show-sorting.html.twig', [
            'bouteilles' => $bouteilles,
        ]);
    }

    /**
     * @Route("/cellier/{id}/bouteille/select", name="bouteille_select")
     */
    public function select(int $id): Response
    {
        $cellier = $this->entityManager->getRepository(Cellier::class)->find($id);

        if (!$cellier) {
            throw $this->createNotFoundException('Cellier non trouvé.');
        }

        return $this->render('bouteille/select.html.twig', [
            'cellier' => $cellier,
        ]);
    }

    /**
     * @Route("/bouteilles/selectAll/{id}", name="bouteille_select_all", methods={"POST"})
     */
    public function selectAllBouteilles(Request $request, Cellier $cellier): Response
    {
        $bouteilles = $this->bouteilleRepository->findAll();

        foreach ($bouteilles as $bouteille) {
            $bouteilleCellier = new BouteilleCellier();
            $bouteilleCellier->setCellier($cellier);
            $bouteilleCellier->setBouteille($bouteille);
            $this->entityManager->persist($bouteilleCellier);
        }

        $this->entityManager->flush();

        return $this->redirectToRoute('cellier_show', ['id' => $cellier->getId()]);
    }

    /**
     * @Route("/bouteilles/select/{id}", name="bouteille_select_post", methods={"POST"})
     */
    public function selectPost(Request $request, Cellier $cellier): Response
    {
        $bouteilleIds = $request->request->all('bouteilles');
        if (!is_array($bouteilleIds)) {
            $bouteilleIds = [];
        }
        
        foreach ($bouteilleIds as $bouteilleId) {
            if (is_int($bouteilleId) || ctype_digit($bouteilleId)) {
                $bouteilleId = (int)$bouteilleId;
                $bouteille = $this->entityManager->getRepository(Bouteille::class)->find($bouteilleId);
                if ($bouteille instanceof Bouteille) {
                    $bouteilleCellier = new BouteilleCellier();
                    $bouteilleCellier->setCellier($cellier);
                    $bouteilleCellier->setBouteille($bouteille);
                    $this->entityManager->persist($bouteilleCellier);
                }
            }
        }

        $this->entityManager->flush();

        return $this->redirectToRoute('cellier_show', ['id' => $cellier->getId()]);
    }
}

templates/bouteille/create.html.twig
{# templates/bouteille/create.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Ajouter une bouteille</h1>

    {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.nom, 'Nom') }}
            {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.nom) }}
        </div>
        
        <div class="form-group">
            {{ form_label(form.prix, 'Prix') }}
            {{ form_widget(form.prix, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.prix) }}
        </div>
        
        <div class="form-group">
            {{ form_label(form.pays, 'Pays') }}
            {{ form_widget(form.pays, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.pays) }}
        </div>
        
        <div class="form-group">
            {{ form_label(form.format, 'Format') }}
            {{ form_widget(form.format, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.format) }}
        </div>

        <div class="form-group">
            {{ form_label(form.lienProduit, 'Lien Produit') }}
            {{ form_widget(form.lienProduit, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.lienProduit) }}
        </div>

        <div class="form-group">
            {{ form_label(form.srcImage, 'Source Image') }}
            {{ form_widget(form.srcImage, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.srcImage) }}
        </div>

        <div class="form-group">
            {{ form_label(form.srcsetImage, 'Source Set Image') }}
            {{ form_widget(form.srcsetImage, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.srcsetImage) }}
        </div>

        <div class="form-group">
            {{ form_label(form.designation, 'Désignation') }}
            {{ form_widget(form.designation, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.designation) }}
        </div>

        <div class="form-group">
            {{ form_label(form.degre, 'Degré') }}
            {{ form_widget(form.degre, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.degre) }}
        </div>

        <div class="form-group">
            {{ form_label(form.tauxSucre, 'Taux de Sucre') }}
            {{ form_widget(form.tauxSucre, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.tauxSucre) }}
        </div>

        <div class="form-group">
            {{ form_label(form.couleur, 'Couleur') }}
            {{ form_widget(form.couleur, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.couleur) }}
        </div>

        <div class="form-group">
            {{ form_label(form.producteur, 'Producteur') }}
            {{ form_widget(form.producteur, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.producteur) }}
        </div>

        <div class="form-group">
            {{ form_label(form.agentPromotion, 'Agent de Promotion') }}
            {{ form_widget(form.agentPromotion, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.agentPromotion) }}
        </div>

        <div class="form-group">
            {{ form_label(form.type, 'Type') }}
            {{ form_widget(form.type, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.type) }}
        </div>

        <div class="form-group">
            {{ form_label(form.millesime, 'Millésime') }}
            {{ form_widget(form.millesime, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.millesime) }}
        </div>

        <div class="form-group">
            {{ form_label(form.cepage, 'Cépage') }}
            {{ form_widget(form.cepage, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.cepage) }}
        </div>

        <div class="form-group">
            {{ form_label(form.region, 'Région') }}
            {{ form_widget(form.region, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.region) }}
        </div>

        <div class="form-group">
            {{ form_label(form.produitQuebec, 'Produit Québec') }}
            {{ form_widget(form.produitQuebec, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.produitQuebec) }}
        </div>

        <div class="form-group">
            {{ form_label(form.pastilleGoutTitre, 'Pastille Goût Titre') }}
            {{ form_widget(form.pastilleGoutTitre, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.pastilleGoutTitre) }}
        </div>

        <div class="form-group">
            {{ form_label(form.pastilleImageSrc, 'Pastille Image Source') }}
            {{ form_widget(form.pastilleImageSrc, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.pastilleImageSrc) }}
        </div>

        <div class="form-group">
            {{ form_label(form.createdAt, 'Créé le') }}
            {{ form_widget(form.createdAt, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.createdAt) }}
        </div>

        <div class="form-group">
            {{ form_label(form.updatedAt, 'Mis à jour le') }}
            {{ form_widget(form.updatedAt, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.updatedAt) }}
        </div>

        <div class="form-group">
            {{ form_label(form.user, 'Utilisateur') }}
            {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.user) }}
        </div>
        
        <button type="submit" class="btn btn-primary">Ajouter</button>
    {{ form_end(form) }}
{% endblock %}

templates/bouteille/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Éditer la bouteille {{ bouteille.nom }}{% endblock %}

{% block body %}
    <body>
        <header>
            Éditer la bouteille {{ bouteille.nom }}
        </header>
        <main class="nav-margin">
            <section class="form-ajouter-bouteille">
                <div class="form-container">
                    <form action="{{ path('bouteille_edit', { 'id': bouteille.id }) }}" method="POST">
                        {{ form_widget(form) }}
                        <button type="submit" class="btn-submit">Enregistrer</button>
                    </form>
                </div>
            </section>
        </main>
    </body>
{% endblock %}

templates/bouteille/show-search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultats de la recherche{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Résultats de la recherche</h1>

    {% if bouteilles is empty %}
        <div class="alert alert-warning" role="alert">
            Aucune bouteille trouvée.
        </div>
    {% else %}
        <div class="list-group">
            {% for bouteille in bouteilles %}
                <a href="{{ path('bouteille_show', {id: bouteille.id}) }}" class="list-group-item list-group-item-action">
                    {{ bouteille.nom }}
                </a>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

templates/bouteille/show-sorting.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bouteilles triées{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Résultats du tri</h1>

    {% if bouteilles is empty %}
        <div class="alert alert-warning" role="alert">
            Aucune bouteille trouvée.
        </div>
    {% else %}
        <div class="list-group">
            {% for bouteille in bouteilles %}
                <a href="{{ path('bouteille_show', {id: bouteille.id}) }}" class="list-group-item list-group-item-action">
                    {{ bouteille.nom }}
                </a>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

templates/bouteille/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Détails de la bouteille{{ bouteille.nom }}{% endblock %}
{% block body %}
<body>
    <header>
        Détails de la bouteille {{ bouteille.nom }}
    </header>
    <main class="nav-margin">
        <section class="card-bouteille">
            <picture>
                <img src="{{ bouteille.srcImage }}" alt="{{ bouteille.nom }}">
            </picture>
            <div class="card-bouteille-content">
                <div class="card-bouteille-info">
                    <h2>{{ bouteille.nom }}</h2>
                    <span>{{ bouteille.type }} | {{ bouteille.format }} | {{ bouteille.pays }}</span>
                    <p>{{ bouteille.prix }} $</p>
                </div>
            </div>
        </section>
    </main>
</body>
{% endblock %}